package tools.debugger.nodes;

import com.oracle.truffle.api.nodes.Node;

/**
 * Abstract node for controlling states (enable or disable) of breakpoints.
 * Implementation of executeCheckIsSetAndEnabled method is generated by Truffle DSL.
 *
 */
public abstract class AbstractBreakpointNode extends Node {
  public abstract boolean executeCheckIsSetAndEnabled();
}
